### ISSUE TITLE
Error with current `main` version

### ISSUE THREAD

**Issue by basvandervlies** [SURFscz/SRAMsync#143]
The changes in the main branch broke the sync
```
root# sram_sync bas_main /opt/sram_sync/etc/hub-lisa.yml
Using version: bas_main
Traceback (most recent call last):
  File "/opt/sram_sync/bas_main/.venv/bin/sync-with-sram", line 33, in <module>
    sys.exit(load_entry_point('SRAMsync', 'console_scripts', 'sync-with-sram')())
  File "/opt/sram_sync/bas_main/.venv/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/sram_sync/bas_main/.venv/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/sram_sync/bas_main/.venv/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/sram_sync/bas_main/.venv/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/sram_sync/bas_main/.venv/src/sramsync/SRAMsync/sync_with_sram.py", line 746, in cli
    cfg = Config(configuration_path, new_eventhandler_args)
  File "/opt/sram_sync/bas_main/.venv/src/sramsync/SRAMsync/config.py", line 189, in __init__
    event_handlers = self.get_event_handlers(self.state, args)
  File "/opt/sram_sync/bas_main/.venv/src/sramsync/SRAMsync/config.py", line 234, in get_event_handlers
    self.config["service"], event_handler_cfg, state, ["sync", "event_handler", "config"]
TypeError: __init__() missing 1 required positional argument: 'args'
```

**Comment by basvandervlies** [comment]
The error is in the `CbaScriptGenerator` class

**Comment by basvandervlies** [comment]
Also an errror in the `notfication` class:
```
oot# sync-with-sram -d -l debug /opt/sram_sync/etc/hub-lisa.yml
Started syncing with SRAM                                                                
Handling configuration: /opt/sram_sync/etc/hub-lisa.yml                 
debug: LDAP: connecting to: ldaps://ldap.sram.surf.nl
debug: LDAP: connected                                                                   
debug: Processing CO: jhlsrf024                                                          
warning: CuaScriptGenerator: CBA CO budget mapping per file has been requested, however file '' does not exists.
debug:   Found new user: jhlsrf024-cvanleeuwe-teacher
error: Missing(email_notification) argument: 'group'                                                                                                                               
debug: SMTP: connecting to: localhost                                                    
debug: SMTP: connected to SMTP host
debug: Disconnecting SMTP server  
```
